"""add sql_job

Revision ID: fccff9c21513
Revises: 65c0a3488f01
Create Date: 2026-09-29 05:33:32.182649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccff9c21513'
down_revision = '65c0a3488f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_fingerprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('canonical_sql', sa.Text(), nullable=False),
    sa.Column('literal_sql', sa.Text(), nullable=True),
    sa.Column('literal_available', sa.Boolean(), nullable=True),
    sa.Column('stmt_type', sa.String(length=16), nullable=False),
    sa.Column('schema_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('sql_target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('db_type', sa.String(length=16), nullable=False),
    sa.Column('conn_url', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.String(length=256), nullable=False),
    sa.Column('extra_conf', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_collect', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sql_exec_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('stmt_type', sa.String(length=16), nullable=False),
    sa.Column('exec_status', sa.String(length=16), nullable=False),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('rows_affected', sa.BigInteger(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('exec_by', sa.String(length=64), nullable=False),
    sa.Column('exec_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['sql_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exec_target_time', 'sql_exec_history', ['target_id', 'exec_at'], unique=False)
    op.create_table('sql_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('since_days', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=16), nullable=True),
    sa.Column('last_run_message', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['sql_target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sql_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('stmt_type', sa.String(length=16), nullable=False),
    sa.Column('pattern_regex', sa.String(length=512), nullable=True),
    sa.Column('allow_exec', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['sql_target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sql_stat_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snap_time', sa.DateTime(), nullable=False),
    sa.Column('executions', sa.BigInteger(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('avg_elapsed_ms', sa.Float(), nullable=True),
    sa.Column('cpu_ms', sa.Float(), nullable=True),
    sa.Column('buffer_gets', sa.BigInteger(), nullable=True),
    sa.Column('rows_processed', sa.BigInteger(), nullable=True),
    sa.Column('disk_reads', sa.BigInteger(), nullable=True),
    sa.Column('optimizer_cost', sa.Float(), nullable=True),
    sa.Column('plan_hash', sa.String(length=32), nullable=True),
    sa.Column('db_snap_id', sa.String(length=64), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fingerprint'], ['sql_fingerprint.fingerprint'], ),
    sa.ForeignKeyConstraint(['target_id'], ['sql_target.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'fingerprint', 'snap_time', name='uk_snap_unique')
    )
    op.create_index('idx_snap_fp_time', 'sql_stat_snapshot', ['fingerprint'], unique=False)
    op.create_index('idx_snap_target_time', 'sql_stat_snapshot', ['target_id', 'snap_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snap_target_time', table_name='sql_stat_snapshot')
    op.drop_index('idx_snap_fp_time', table_name='sql_stat_snapshot')
    op.drop_table('sql_stat_snapshot')
    op.drop_table('sql_policy')
    op.drop_table('sql_job')
    op.drop_index('idx_exec_target_time', table_name='sql_exec_history')
    op.drop_table('sql_exec_history')
    op.drop_table('sql_target')
    op.drop_table('sql_fingerprint')
    # ### end Alembic commands ###
